[package]
name = "fixed-cost-search"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Fixed cost search on weighted graphs"

[dependencies]
graphs = { git = "https://github.com/TiagoCavalcante/graphs", tag = "0.3.1" }
ordered-float = "3.0.0"
